import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

// Styles for the PDF receipt
const styles = StyleSheet.create({
  page: {
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 32,
    fontSize: 12,
    color: '#111827'
  },
  header: {
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    borderBottomStyle: 'solid'
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    color: '#111827'
  },
  subTitle: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4
  },
  section: {
    marginTop: 16
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6
  },
  label: {
    color: '#6b7280'
  },
  value: {
    color: '#111827',
    fontWeight: 600
  },
  footer: {
    marginTop: 24,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    borderTopStyle: 'solid',
    color: '#6b7280',
    fontSize: 10
  }
});

/**
 * ReceiptDocument
 * Props:
 *  - donor: { name, email }
 *  - donation: { id, date, amount, cause, receipt }
 *  - organization?: { name }
 */
export function ReceiptDocument({ donor, donation, organization }) {
  const orgName = organization?.name || 'Relief Connect';
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Donation Receipt</Text>
          <Text style={styles.subTitle}>{orgName}</Text>
        </View>

        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Receipt No.</Text>
            <Text style={styles.value}>{donation?.receipt || `RC-${donation?.id}`}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{donation?.date}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={{ fontWeight: 700, marginBottom: 8 }}>Donor Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Name</Text>
            <Text style={styles.value}>{donor?.name || 'Anonymous Donor'}</Text>
          </View>
          {donor?.email ? (
            <View style={styles.row}>
              <Text style={styles.label}>Email</Text>
              <Text style={styles.value}>{donor.email}</Text>
            </View>
          ) : null}
        </View>

        <View style={styles.section}>
          <Text style={{ fontWeight: 700, marginBottom: 8 }}>Donation Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Cause</Text>
            <Text style={styles.value}>{donation?.cause}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Amount</Text>
            <Text style={styles.value}>${Number(donation?.amount).toLocaleString()}</Text>
          </View>
          <View style={{ marginTop: 8 }}>
            <Text style={{ color: '#374151' }}>
              Thank you for your generous contribution. This receipt acknowledges that a donation was
              received by {orgName}. No goods or services were provided in exchange for this donation.
            </Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text>Generated by Relief Connect</Text>
          <Text>Keep this receipt for your records.</Text>
        </View>
      </Page>
    </Document>
  );
}

export default ReceiptDocument;


